name: gaimzone
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  circular_countdown_timer: ^0.2.4
  flutter_svg: ^2.0.7
  group_list_view: ^1.1.1
  flutter_confetti: ^0.5.1
  flutter_speed_dial: ^7.0.0
  timer_count_down: ^2.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.11
  widget_tooltip: ^1.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsLight.ttf
        - asset: assets/fonts/PoppinsRegular.ttf
        - asset: assets/fonts/PoppinsMedium.ttf
        - asset: assets/fonts/PoppinsSemiBold.ttf
        - asset: assets/fonts/PoppinsBold.ttf

    - family: Lufga
      fonts:
        - asset: assets/fonts/LufgaLight.ttf
        - asset: assets/fonts/LufgaRegular.ttf
        - asset: assets/fonts/LufgaMedium.ttf
        - asset: assets/fonts/LufgaSemiBold.ttf
        - asset: assets/fonts/LufgaBold.ttf


